// <auto-generated />
using System;
using Maple2.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Maple2.Server.World.Migrations
{
    [DbContext(typeof(Ms2Context))]
    [Migration("20240518200914_ServerInfo")]
    partial class ServerInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Maple2.Database.Model.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("ActiveGoldPass")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime>("LastModified")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("binary(16)");

                    b.Property<string>("MarketLimits")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int>("MaxCharacters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4);

                    b.Property<bool>("Online")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PremiumRewardsClaimed")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<long>("PremiumTime")
                        .HasColumnType("bigint");

                    b.Property<long>("PrestigeCurrentExp")
                        .HasColumnType("bigint");

                    b.Property<long>("PrestigeExp")
                        .HasColumnType("bigint");

                    b.Property<int>("PrestigeLevel")
                        .HasColumnType("int");

                    b.Property<int>("PrestigeLevelsGained")
                        .HasColumnType("int");

                    b.Property<string>("PrestigeMissions")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("PrestigeRewardsClaimed")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<long>("SurvivalExp")
                        .HasColumnType("bigint");

                    b.Property<int>("SurvivalGoldLevelRewardClaimed")
                        .HasColumnType("int");

                    b.Property<int>("SurvivalLevel")
                        .HasColumnType("int");

                    b.Property<int>("SurvivalSilverLevelRewardClaimed")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Maple2.Database.Model.Achievement", b =>
                {
                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("int");

                    b.Property<long>("Counter")
                        .HasColumnType("bigint");

                    b.Property<int>("CurrentGrade")
                        .HasColumnType("int");

                    b.Property<bool>("Favorite")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Grades")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int>("RewardGrade")
                        .HasColumnType("int");

                    b.HasKey("OwnerId", "Id");

                    b.ToTable("Achievement");
                });

            modelBuilder.Entity("Maple2.Database.Model.Buddy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("BuddyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("BuddyId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Buddy");
                });

            modelBuilder.Entity("Maple2.Database.Model.Character", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<short>("Channel")
                        .HasColumnType("smallint");

                    b.Property<string>("Cooldown")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime>("DeleteTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("Job")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModified")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<short>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.Property<string>("Mastery")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int>("ReturnMapId")
                        .HasColumnType("int");

                    b.Property<string>("SkinColor")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Character");
                });

            modelBuilder.Entity("Maple2.Database.Model.CharacterConfig", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<string>("DeathPenalty")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("FavoriteDesigners")
                        .HasColumnType("json");

                    b.Property<string>("FavoriteStickers")
                        .HasColumnType("json");

                    b.Property<string>("GatheringCounts")
                        .HasColumnType("json");

                    b.Property<string>("HotBars")
                        .HasColumnType("json");

                    b.Property<string>("KeyBinds")
                        .HasColumnType("json");

                    b.Property<string>("Lapenshards")
                        .HasColumnType("json");

                    b.Property<DateTime>("LastModified")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SkillCooldowns")
                        .HasColumnType("json");

                    b.Property<string>("SkillMacros")
                        .HasColumnType("json");

                    b.Property<string>("StatAllocation")
                        .HasColumnType("json");

                    b.Property<string>("Wardrobes")
                        .HasColumnType("json");

                    b.HasKey("CharacterId");

                    b.ToTable("character-config", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.CharacterUnlock", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<string>("CollectedItems")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Emotes")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Expand")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("FishAlbum")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<short>("HairSlotExpand")
                        .HasColumnType("smallint");

                    b.Property<string>("InteractedObjects")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime>("LastModified")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Maps")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("MasteryRewardsClaimed")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Pets")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("StickerSets")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Taxis")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Titles")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("CharacterId");

                    b.ToTable("character-unlock", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.Club", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastModified")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<long>("LeaderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("LeaderId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Club");
                });

            modelBuilder.Entity("Maple2.Database.Model.ClubMember", b =>
                {
                    b.Property<long>("ClubId")
                        .HasColumnType("bigint");

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.HasKey("ClubId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("club-member", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.Event.GameEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventInfo")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("game-event", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.Event.GameEventUserValue", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long>("ExpirationTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CharacterId", "EventId", "Type");

                    b.ToTable("game-event-user-value", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.Guild", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Buffs")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Emblem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("Focus")
                        .HasColumnType("int");

                    b.Property<int>("Funds")
                        .HasColumnType("int");

                    b.Property<int>("HouseRank")
                        .HasColumnType("int");

                    b.Property<int>("HouseTheme")
                        .HasColumnType("int");

                    b.Property<long>("LeaderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notice")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Npcs")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Posters")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Ranks")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.HasIndex("LeaderId")
                        .IsUnique();

                    b.ToTable("guild", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.GuildApplication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ApplicantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("GuildId");

                    b.ToTable("guild-application", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.GuildMember", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CheckinTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DailyDonationCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("DonationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("Rank")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("TotalContribution")
                        .HasColumnType("int");

                    b.Property<int>("WeeklyContribution")
                        .HasColumnType("int");

                    b.HasKey("GuildId", "CharacterId");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("guild-member", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.Home", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("ArchitectScore")
                        .HasColumnType("int");

                    b.Property<byte>("Area")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)4);

                    b.Property<byte>("Background")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Camera")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("CurrentArchitectScore")
                        .HasColumnType("int");

                    b.Property<byte>("Height")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)3);

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Lighting")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Passcode")
                        .HasColumnType("longtext");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("AccountId");

                    b.ToTable("Home");
                });

            modelBuilder.Entity("Maple2.Database.Model.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Appearance")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Binding")
                        .HasColumnType("json");

                    b.Property<string>("CoupleInfo")
                        .HasColumnType("json");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Enchant")
                        .HasColumnType("json");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GachaDismantleId")
                        .HasColumnType("int");

                    b.Property<short>("GlamorForges")
                        .HasColumnType("smallint");

                    b.Property<byte>("Group")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LimitBreak")
                        .HasColumnType("json");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int>("RemainUses")
                        .HasColumnType("int");

                    b.Property<short>("Slot")
                        .HasColumnType("smallint");

                    b.Property<string>("Socket")
                        .HasColumnType("json");

                    b.Property<string>("Stats")
                        .HasColumnType("json");

                    b.Property<string>("SubType")
                        .HasColumnType("json");

                    b.Property<int>("TimeChangedOption")
                        .HasColumnType("int");

                    b.Property<string>("Transfer")
                        .HasColumnType("json");

                    b.Property<long>("UnlockTime")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Maple2.Database.Model.ItemStorage", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<short>("Expand")
                        .HasColumnType("smallint");

                    b.Property<long>("Meso")
                        .HasColumnType("bigint");

                    b.HasKey("AccountId");

                    b.ToTable("item-storage", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.Mail", b =>
                {
                    b.Property<long>("ReceiverId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContentArgs")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ReadTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SendTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TitleArgs")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("ReceiverId", "Id");

                    b.ToTable("Mail");
                });

            modelBuilder.Entity("Maple2.Database.Model.MesoListing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastModified")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CharacterId");

                    b.ToTable("meso-market", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.PetConfig", b =>
                {
                    b.Property<long>("ItemUid")
                        .HasColumnType("bigint");

                    b.Property<string>("LootConfig")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("PotionConfigs")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("ItemUid");

                    b.ToTable("pet-config", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.PremiumMarketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BannerLabel")
                        .HasColumnType("int");

                    b.Property<string>("BannerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("BonusQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("CurrencyType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("Giftable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ItemDuration")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("JobRequirement")
                        .HasColumnType("int");

                    b.Property<byte>("Label")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<bool>("PcCafe")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("PromoData")
                        .HasColumnType("json");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte>("Rarity")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("RequireAchievementId")
                        .HasColumnType("int");

                    b.Property<int>("RequireAchievementRank")
                        .HasColumnType("int");

                    b.Property<short>("RequireMaxLevel")
                        .HasColumnType("smallint");

                    b.Property<short>("RequireMinLevel")
                        .HasColumnType("smallint");

                    b.Property<bool>("RestockUnavailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("SalePrice")
                        .HasColumnType("bigint");

                    b.Property<int>("SalesCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("SellBeginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SellEndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("ShowSaleTime")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TabId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("premium-market-item", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.Quest", b =>
                {
                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CompletionCount")
                        .HasColumnType("int");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<long>("EndTime")
                        .HasColumnType("bigint");

                    b.Property<long>("StartTime")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<bool>("Track")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("OwnerId", "Id");

                    b.ToTable("Quest");
                });

            modelBuilder.Entity("Maple2.Database.Model.ServerInfo", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Key");

                    b.ToTable("server-info", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.Shop.BeautyShop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("RecolorCostAmount")
                        .HasColumnType("int");

                    b.Property<byte>("RecolorCostCurrencyType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("RecolorCostItemId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceCostAmount")
                        .HasColumnType("int");

                    b.Property<byte>("ServiceCostCurrencyType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("ServiceCostItemId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceRewardItemId")
                        .HasColumnType("int");

                    b.Property<int>("ShopSubType")
                        .HasColumnType("int");

                    b.Property<int>("ShopType")
                        .HasColumnType("int");

                    b.Property<byte>("Unknown1")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Unknown2")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("beauty-shop", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.Shop.BeautyShopEntry", b =>
                {
                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("CostAmount")
                        .HasColumnType("int");

                    b.Property<int>("CostItemId")
                        .HasColumnType("int");

                    b.Property<byte>("CostType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Label")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("RequireAchievementId")
                        .HasColumnType("int");

                    b.Property<byte>("RequireAchievementRank")
                        .HasColumnType("tinyint unsigned");

                    b.Property<short>("RequireLevel")
                        .HasColumnType("smallint");

                    b.HasKey("ShopId", "ItemId");

                    b.ToTable("beauty-shop-entry", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.Shop.CharacterShopData", b =>
                {
                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Interval")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("RestockCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("RestockTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ShopId", "OwnerId");

                    b.ToTable("character-shop-data", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.Shop.CharacterShopItemData", b =>
                {
                    b.Property<int>("ShopItemId")
                        .HasColumnType("int");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("StockPurchased")
                        .HasColumnType("int");

                    b.HasKey("ShopItemId", "OwnerId");

                    b.HasIndex("ShopId");

                    b.ToTable("character-shop-item-data", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.Shop.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("DisableBuyback")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DisplayNew")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HideStats")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HideUnuseable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("OpenWallet")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RandomizeOrder")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RestockData")
                        .HasColumnType("json");

                    b.Property<DateTime>("RestockTime")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Skin")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("shop", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.Shop.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AutoPreviewEquip")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CurrencyItemId")
                        .HasColumnType("int");

                    b.Property<byte>("CurrencyType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("IconCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<byte>("Label")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.Property<byte>("Rarity")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("RequireAchievementId")
                        .HasColumnType("int");

                    b.Property<int>("RequireAchievementRank")
                        .HasColumnType("int");

                    b.Property<byte>("RequireChampionshipGrade")
                        .HasColumnType("tinyint unsigned");

                    b.Property<short>("RequireChampionshipJoinCount")
                        .HasColumnType("smallint");

                    b.Property<int>("RequireFameGrade")
                        .HasColumnType("int");

                    b.Property<short>("RequireGuildMerchantLevel")
                        .HasColumnType("smallint");

                    b.Property<byte>("RequireGuildMerchantType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("RequireGuildTrophy")
                        .HasColumnType("int");

                    b.Property<short>("RequireQuestAllianceId")
                        .HasColumnType("smallint");

                    b.Property<string>("RestrictedBuyData")
                        .HasColumnType("json");

                    b.Property<int>("SalePrice")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("StockCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("shop-item", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.SkillTab", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("CharacterId", "Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("skill-tab", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.SoldMesoListing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ListedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SoldTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("meso-market-sold", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.SoldUgcMarketItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<long>("Profit")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SoldTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("ugc-market-item-sold", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.SystemBanner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Function")
                        .HasColumnType("int");

                    b.Property<string>("FunctionParameter")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("system-banner", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.UgcMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("ApartmentNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Indoor")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastModified")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("OwnerId");

                    b.ToTable("ugcmap", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.UgcMapCube", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<float>("Rotation")
                        .HasColumnType("float");

                    b.Property<string>("Template")
                        .HasColumnType("json");

                    b.Property<long>("UgcMapId")
                        .HasColumnType("bigint");

                    b.Property<sbyte>("X")
                        .HasColumnType("tinyint");

                    b.Property<sbyte>("Y")
                        .HasColumnType("tinyint");

                    b.Property<sbyte>("Z")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("UgcMapId");

                    b.ToTable("ugcmap-cube", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.UgcMarketItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ListingEndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Look")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PromotionEndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SalesCount")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("TabId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.ToTable("ugc-market-item", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.UgcResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastModified")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("ugcresource", (string)null);
                });

            modelBuilder.Entity("Maple2.Database.Model.Buddy", b =>
                {
                    b.HasOne("Maple2.Database.Model.Character", "BuddyCharacter")
                        .WithMany()
                        .HasForeignKey("BuddyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maple2.Database.Model.Character", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuddyCharacter");
                });

            modelBuilder.Entity("Maple2.Database.Model.Character", b =>
                {
                    b.HasOne("Maple2.Database.Model.Account", null)
                        .WithMany("Characters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maple2.Database.Model.CharacterConfig", b =>
                {
                    b.HasOne("Maple2.Database.Model.Character", null)
                        .WithOne()
                        .HasForeignKey("Maple2.Database.Model.CharacterConfig", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Maple2.Database.Model.SkillBook", "SkillBook", b1 =>
                        {
                            b1.Property<long>("CharacterConfigCharacterId")
                                .HasColumnType("bigint");

                            b1.Property<long>("ActiveSkillTabId")
                                .HasColumnType("bigint");

                            b1.Property<int>("MaxSkillTabs")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(1);

                            b1.HasKey("CharacterConfigCharacterId");

                            b1.HasIndex("ActiveSkillTabId")
                                .IsUnique();

                            b1.ToTable("character-config");

                            b1.HasOne("Maple2.Database.Model.SkillTab", null)
                                .WithOne()
                                .HasForeignKey("Maple2.Database.Model.CharacterConfig.SkillBook#Maple2.Database.Model.SkillBook", "ActiveSkillTabId")
                                .HasPrincipalKey("Maple2.Database.Model.SkillTab", "Id")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("CharacterConfigCharacterId");
                        });

                    b.Navigation("SkillBook");
                });

            modelBuilder.Entity("Maple2.Database.Model.CharacterUnlock", b =>
                {
                    b.HasOne("Maple2.Database.Model.Character", null)
                        .WithOne()
                        .HasForeignKey("Maple2.Database.Model.CharacterUnlock", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maple2.Database.Model.Club", b =>
                {
                    b.HasOne("Maple2.Database.Model.Character", null)
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maple2.Database.Model.ClubMember", b =>
                {
                    b.HasOne("Maple2.Database.Model.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maple2.Database.Model.Club", null)
                        .WithMany("Members")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Maple2.Database.Model.Event.GameEventUserValue", b =>
                {
                    b.HasOne("Maple2.Database.Model.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maple2.Database.Model.Guild", b =>
                {
                    b.HasOne("Maple2.Database.Model.Character", null)
                        .WithOne()
                        .HasForeignKey("Maple2.Database.Model.Guild", "LeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maple2.Database.Model.GuildApplication", b =>
                {
                    b.HasOne("Maple2.Database.Model.Character", null)
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maple2.Database.Model.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maple2.Database.Model.GuildMember", b =>
                {
                    b.HasOne("Maple2.Database.Model.Character", "Character")
                        .WithOne()
                        .HasForeignKey("Maple2.Database.Model.GuildMember", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maple2.Database.Model.Guild", null)
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Maple2.Database.Model.Home", b =>
                {
                    b.HasOne("Maple2.Database.Model.Account", null)
                        .WithOne()
                        .HasForeignKey("Maple2.Database.Model.Home", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maple2.Database.Model.ItemStorage", b =>
                {
                    b.HasOne("Maple2.Database.Model.Account", null)
                        .WithOne()
                        .HasForeignKey("Maple2.Database.Model.ItemStorage", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maple2.Database.Model.Mail", b =>
                {
                    b.HasOne("Maple2.Database.Model.Character", null)
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maple2.Database.Model.MesoListing", b =>
                {
                    b.HasOne("Maple2.Database.Model.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maple2.Database.Model.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maple2.Database.Model.PetConfig", b =>
                {
                    b.HasOne("Maple2.Database.Model.Item", null)
                        .WithOne()
                        .HasForeignKey("Maple2.Database.Model.PetConfig", "ItemUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maple2.Database.Model.Shop.BeautyShopEntry", b =>
                {
                    b.HasOne("Maple2.Database.Model.Shop.BeautyShop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maple2.Database.Model.Shop.CharacterShopData", b =>
                {
                    b.HasOne("Maple2.Database.Model.Shop.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maple2.Database.Model.Shop.CharacterShopItemData", b =>
                {
                    b.HasOne("Maple2.Database.Model.Shop.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maple2.Database.Model.Shop.ShopItem", null)
                        .WithMany()
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maple2.Database.Model.Shop.ShopItem", b =>
                {
                    b.HasOne("Maple2.Database.Model.Shop.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maple2.Database.Model.SkillTab", b =>
                {
                    b.HasOne("Maple2.Database.Model.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maple2.Database.Model.SoldUgcMarketItem", b =>
                {
                    b.HasOne("Maple2.Database.Model.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maple2.Database.Model.UgcMapCube", b =>
                {
                    b.HasOne("Maple2.Database.Model.UgcMap", null)
                        .WithMany("Cubes")
                        .HasForeignKey("UgcMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maple2.Database.Model.Account", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Maple2.Database.Model.Club", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Maple2.Database.Model.Guild", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Maple2.Database.Model.UgcMap", b =>
                {
                    b.Navigation("Cubes");
                });
#pragma warning restore 612, 618
        }
    }
}
